name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Select XCode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Build and Test
        run: |
          xcodebuild -scheme Class\ Tools -destination platform=iOS\ Simulator,OS=15.0,name=iPhone\ 11 \
          clean test \
          | xcpretty \
          && exit ${PIPESTATUS[0]}
